name: Podspec Push

on:
  push:
    tags:
      - v*

jobs:
  lint:
    name: "CocoaPods Trunk Push"
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.4.app
      - name: Test Specs
        run: |
          export CI=1
          pod lib lint --verbose --no-clean --swift-version=5.3 --allow-warnings DonkeyLockKit.podspec
          pod trunk push --allow-warnings DonkeyLockKit.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
